# Generated by Django 4.2.4 on 2023-09-13 00:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header_title', models.CharField(max_length=100)),
                ('sect_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('about_sect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_sect', to='content.about')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
                ('see_more_text', models.CharField(max_length=20)),
                ('personal_project_title', models.CharField(default='Personal Projects.', max_length=100)),
                ('background_project_title', models.CharField(default='Background Projects.', max_length=100)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSkills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='_', max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile')], default='Desktop', max_length=7)),
                ('typeSoftHard', models.CharField(choices=[('Soft', 'Soft'), ('Hard', 'Hard')], default='Soft', max_length=7)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_skills', to='content.services')),
            ],
        ),
        migrations.CreateModel(
            name='SectSubtitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('landing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sect_subtitle', to='content.landing')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_cards', to='content.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('background_image', models.CharField(max_length=100)),
                ('url_to_project', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Personal', 'Personal'), ('Background', 'Background')], default='Background', max_length=10)),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.works')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('link_text', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=200)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='content.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='content.content'),
        ),
        migrations.CreateModel(
            name='AboutContentTexts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('about_content_texts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_content_texts', to='content.aboutcontent')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about', to='content.content'),
        ),
    ]
