# Generated by Django 4.2.4 on 2023-09-01 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header_title', models.CharField(max_length=100)),
                ('sect_title', models.CharField(max_length=100)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('about_sect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_sect', to='content.about')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sect_title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=20)),
                ('see_more_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='sectsubtitle',
            name='test',
        ),
        migrations.CreateModel(
            name='ServicesSkills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_skills', to='content.services')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_cards', to='content.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sect', to='content.works')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('background_image', models.CharField(max_length=100)),
                ('url_to_project', models.CharField(max_length=100)),
                ('project_sect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.works')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=5)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile', to='content.servicesskills')),
            ],
        ),
        migrations.CreateModel(
            name='DesktopSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=5)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop', to='content.servicesskills')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('link_text', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='content.works')),
            ],
        ),
        migrations.CreateModel(
            name='AboutContentTexts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('about_content_texts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_content_texts', to='content.aboutcontent')),
            ],
        ),
    ]
