# Generated by Django 4.2.4 on 2023-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_about_aboutcontent_contact_resume_services_works_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileskill',
            name='service',
        ),
        migrations.AddField(
            model_name='servicesskills',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesskills',
            name='title',
            field=models.CharField(default='_', max_length=50),
        ),
        migrations.AddField(
            model_name='servicesskills',
            name='type',
            field=models.CharField(default='desktop', max_length=5),
        ),
        migrations.DeleteModel(
            name='DesktopSkill',
        ),
        migrations.DeleteModel(
            name='MobileSkill',
        ),
    ]
