# Generated by Django 4.2.4 on 2023-09-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_mobileskill_service_servicesskills_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='content.content'),
        ),
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume', to='content.content'),
        ),
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='content.content'),
        ),
        migrations.AddField(
            model_name='works',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='content.content'),
        ),
    ]
