# Generated by Django 4.2.4 on 2023-09-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contact_content_resume_content_services_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesskills',
            name='type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile')], default='desktop', max_length=7),
        ),
    ]
