# Generated by Django 4.2.4 on 2023-09-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_servicesskills_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesskills',
            name='typeSoftHard',
            field=models.CharField(choices=[('Soft', 'Soft'), ('Hard', 'Hard')], default='Soft', max_length=7),
        ),
        migrations.AlterField(
            model_name='servicesskills',
            name='type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile')], default='Desktop', max_length=7),
        ),
    ]
