# Generated by Django 4.2.4 on 2023-09-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_servicesskills_typesofthard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_sect',
            new_name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Background', 'Background')], default='Background', max_length=10),
        ),
        migrations.AddField(
            model_name='works',
            name='background_project_title',
            field=models.CharField(default='Background Projects.', max_length=100),
        ),
        migrations.AddField(
            model_name='works',
            name='personal_project_title',
            field=models.CharField(default='Personal Projects.', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProjectSection',
        ),
    ]
