# Generated by Django 4.2.4 on 2023-09-11 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_project_sect_project_projects_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='content.contact'),
        ),
    ]
