# Generated by Django 4.2.4 on 2023-09-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_contactcard_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='url_link',
            field=models.CharField(max_length=200),
        ),
    ]
